### ISSUE TITLE
Email should be unique for many accounts

### ISSUE THREAD

**Issue by michelsup** [sentora/sentora-core#134]
I do not see the point to refuse an email to be the contact email for many accounts.
I should be able to order as many packages I want without creating an unique email for each, thus bringing complication to manage them.

if (!fs_director::CheckForEmptyValue(self::$not_unique_email)) {
            return ui_sysmessage::shout(ui_language::translate("Another user account is already using this email address."), "zannounceerror");
        }

**Comment by artfusion** [comment]
@michelsup I was thinking the same thing, did you do a workaround? I need to create multiple accounts with my webmaster email address, rather than the client

**Comment by michelsup** [comment]
To be honest I don't remember if I changed this portion of code. There was much to tweak and so little pulse ( https://github.com/sentora/sentora-core/pulse/monthly ) that I got fed up and just kept one server with Sentora. R.I.P.

**Comment by artfusion** [comment]
what did you end up using for a control panel then. sentora seems to have a lot of promise

**Comment by michelsup** [comment]
I returned to my less sexy but more secure and productive own scripts.

**Comment by Caffe1neAdd1ct** [comment]
I have one issue with this request regarding the password reset functionality

It uses just an email address, so would send you reset links for each account, or you would be unable to reset the second/third/etc accounts due to only one reset link going out for the first account.

![screenshot from 2015-09-28 12 50 27](https://cloud.githubusercontent.com/assets/1327332/10134707/c0c53464-65df-11e5-830f-cc94fae1f3bf.png)

We could look at having the reset page require two pieces of information, username & email, would be have to be a unique combination.
