### ISSUE TITLE
After user is deleted records in database are not removed.

### ISSUE THREAD

**Issue by IliaIdakiev** [sentora/sentora-core#165]
After user is deleted records in database are not removed. I have to manually delete them if I want to re-register the user.

**Comment by TGates71** [comment]
That is correct. It is by design. It keeps the records in case there are any issues with that user's account like abuse etc.
On that note, I have just released a new module that does what you are asking: http://forums.sentora.org/showthread.php?tid=1617
Currently it does not backup any records you delete, it just completely removes the selected records permanently.

**Comment by IliaIdakiev** [comment]
Thank you!
