### ISSUE TITLE
Sentora shows nothing in google chrome and firefox when using cloudflare

### ISSUE THREAD

**Issue by KaidenP** [sentora/sentora-core#177]
Trying to go to the sentora login page, Chrome shows nothing, however the html is there to show. IE works fine.

**EDIT:** As a note, this is on a fresh install on a openvz vps running centos6
**EDIT2:** Firefox does this as well

**Comment by kkprince1998** [comment]
I figured out that this is a cloudflare issue. I have fixed it, and I am submitting my fix as a pull request.

**Comment by 5050** [comment]
Hi, 
I saw you change. Adding the directive data-cfasync may work, but is it the correct solution ?
I am thinking about the missing declaration type="text/javascript" which is reported as mandatory by www validator.
If nobody confim what i feel, i'll validate the pull, but i'm afraid that it may remains a lot of other <script> tags to parse to not forget any !

**Comment by eByte23** [comment]
Hi,
I think you would be correct in assuming this, I can't test this but I definitely think holding back on pr till it is tested.

**Comment by kkprince1998** [comment]
@5050 adding the type attribute only allows it to be verified. It works regardless, and the only reason I never added it was because it wasn't there in the first place.

If you want I can certainly add it into the pull request, but I would think that this is a different issue, so I thought it should go in its own pull request, but please correct me if I am wrong.

**Comment by Caffe1neAdd1ct** [comment]
@kkprince1998 Please add the type declaration to the PR :+1:  I'll be reviewing PR's soon.

**Comment by TGates71** [comment]
Cloudflare specific with an alternate solution available.
