### ISSUE TITLE
My webserver got hacked

### ISSUE THREAD

**Issue by MoBadawy** [sentora/sentora-core#303]
I think my web server that is based on Sentora got hacked.

I have 6 sites on that web server and there is 3 of them when you go to a 404 page it's redirect to an AD like pop ads.
For ex. I have this site www.example.com and if some one go to www.example.com/info.php and this page "info.php" don't exist instead of getting 404 page it's redirect him to some ads in another sites.

I think that apache need to update.

**Comment by jd1pinoy** [comment]
Is your website uaing WP?

**Comment by MoBadawy** [comment]
@jd1pinoy One of the sites that has the problem is WordPress.

**Comment by jd1pinoy** [comment]
Maybe you have installed a plugin or a theme that has a base64 which redirects to an ads. 

Let's also wait for someone that is updated on a related issue.

**Comment by MoBadawy** [comment]
@jd1pinoy I thought of that too, So I removed the whole wordpress files and made index.php file and put it in some words and have the same problem with the 404 pages.

**Comment by jd1pinoy** [comment]
Make sure to clear your browser cache and try again.

**Comment by MrKaKisen** [comment]
Does it occur on all sites or just one?

**Comment by MBlagui** [comment]
1. Use the forum for support.
2. seem you have 404 pages >> likely a setup mess here. Either permission or host not configured. When you created the new file did you use root?

Once again my advice use the forums for support:

http://forums.sentora.org/

closing it & please open a new thread in the forum and we do our best to help you.

**Comment by MoBadawy** [comment]
LOL TGates71 very funny I said that my 3 sites got hacked and just one of them is wordpress.

And yes My webserver got hacked because my public html folder doesn't has any files but index.php and it's make the redirects

**Comment by Ron-e** [comment]
Have you customized your Sentora install? maybe something like updated php?

**Comment by TGates71** [comment]
Is Suhosin/Open_basedir disabled for any accounts? If so, that is more than likely the problem. Disabling the security layers will open up your server for hackers through faulty Wordpress plugins. Did you check your logs? It should show how they got in. Either brute force on FTP or even SSH if you are using a password instead of key files. I was able to track a hack to my server from a client's weak FTP password.

**Comment by chongma** [comment]
i have had several wordpress installations hacked.  it was normally because i didn't keep them updated.  you need to follow the wordpress guide for hardening the security.  some people also move the login page away from the default location so it can't be brute force cracked.  there may be a plugin that does it all for you
