### ISSUE TITLE
DKIM DNS MySQL Truncation

### ISSUE THREAD

**Issue by meakajon** [sentora/sentora-core#52]
There is a problem with saving the DKIM Key to the TXT database Table.

Table [zpanel_core].[x_dns]
[dn_target_vc] varchar(100)

Which is way to small for the encoded DKIM Key. Which is also still being lowercased in the PHP.

**Comment by bobsta63** [comment]
Planning to get this fix and opendkim implemented in a separate branch (for testing) over the weekend.

**Comment by bobsta63** [comment]
After looking at the issue this morning, I've located the code in the existing Sentora master branch which appears to NOT be lower-casing the TXT target content so that *should* be ok now (lines 1104 - 1108 in modules/dns-manager/code/controller.ext.php)

For now, as increasing the DB column length isn't goign to have a massive impact on this release I'll do that to ensure that for the first release of Sentora the DKIM/TXT record truncation/limit is fixed.

**Comment by bobsta63** [comment]
After more investigation this evening I've found that @TGates71 has already increased the DNS target address length from 100 to 255 characters, I therefore believe that no further chages are required.

I'll close this bug for now as it should be ok in the latest beta release, if you can test and re-open this issue if you are still not able to add the TXT record.

**Comment by heberth80** [comment]
I can confirm that the issue has been fixed on the RC3 I just installed. I used to do fix it manually on zpanel.

**Comment by bobsta63** [comment]
Thanks for confirming the fix in RC3 :)
